# -*- mode: ruby -*-
# vi: set ft=ruby :

# Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "box-cutter/ubuntu1404-desktop"

  config.vm.hostname = "tapqa"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.name = "tapqa_dev"
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
    sudo apt-get update
    sudo apt-get install -y openjdk-7-jdk build-essential git nodejs
    RUBY_VERSION="2.1.9"
    sudo apt-get -y update
    if ! type rvm >/dev/null 2>&1; then
      curl -sSL https://rvm.io/mpapis.asc | sudo gpg --import -
      curl -L https://get.rvm.io | bash -s stable
      source /etc/profile.d/rvm.sh
    fi

    if ! rvm list rubies ruby | grep ruby-${RUBY_VERSION}; then
      rvm install ${RUBY_VERSION}
    fi

    rvm --default use ${RUBY_VERSION}
  SHELL

end
